$(function(){
    $( "#menu" ).menu();
});
$(document).ready(function(){
	$("#Style1").css("background-color","inherit");
	$("#Style2").css("background-color","inherit");
	$("#Style3").css("background-color","inherit");
	$( ".DetailText" ).each(function() {
		$(this).css("background-color","cornflowerblue");
    });
	$("#LoadAXCPictures").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/AXC/HTML/Pictures.php");
	});
	$("#LoadAXCAllScoreTable").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/AXC/HTML/Scoring/Tables/Search-By/All.php");
	});
	$("#LoadAXCImageTable").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/AXC/HTML/Tables/Table.php");
	});
	$("#LoadImagesAXCSlideshow").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/AXC/Slideshow/Slideshow.php");
	});
	$("#LoadImagesCapturedChart").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/AXC/Charts/HTML/ImagesCaptured/ImagesCaptured.php");
	});
	$("#LoadDatabaseBarChart").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/AXC/Charts/HTML/DatabaseQuery/BarChart.php");
	});
	$("#LoadDeviceBarChart").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/AXC/Charts/HTML/DeviceQuery/BarChart.php");
	});
	$("#LoadPredictChart").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/AXC/Charts/HTML/ImagesCaptured/Predict.php");
	});
	$("#LoadYearlyChart").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/AXC/Charts/HTML/Reports/Yearly.php");
	});
	$("#LoadAboutModal").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Modals/About/Modal.php");
	});
	$("#LoadSPHomePage").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/SP/Home/Page.php");
	});
	$("#LoadSPPaperworkPage").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/SP/Paperwork/Page.php");
	});
	$("#LoadDeveloperHomeContent").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/Developer/Home/Page.php");
	});
	$("#LoadUserIdeasContent").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Program/Include/Developer/User-Ideas/Page.php");
	});
	$("#LoadBackgroundContentOn").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/Components/Elements/Background/Year/HTML/Canvas.php");
	});
	$("#LoadHeaderModal").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/Layouts/Info/Modals/Header/Page.php");
	});
	$("#LoadNavbarModal").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/Layouts/Info/Modals/Navbar/Page.php");
	});
	$("#LoadCSSModal").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/Layouts/Info/Modals/CSS/Page.php");
	});
	$("#LoadJSModal").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/Layouts/Info/Modals/JS/Page.php");
	});
	$("#HomePageAPI").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/Home-Page/Info/Page.php");
	});
	$("#AboutPageAPI").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/About-Page/Info/Page.php");
	});
	$("#LoadAllInternalComponents").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/Components/Info/Page.php");
	});
	$("#LoadImprovementsModal").click(function(){
		$("#LoadContent").load("http://127.0.0.0/Local-Server-Website/Framework/API/Improvements/Modal/Modal.php");
	});
	$("#LoadMenu2").click(function(){
		$("#FullImprovements").empty();
		$("#SmallImprovements").load("http://127.0.0.0/Local-Server-Website/Framework/API/Improvements/Side-Menu/Half/Page.php");
		$("#ExtraMenus").load("http://127.0.0.0/Local-Server-Website/Framework/API/App/Layouts/Components/HTML/App-Layout.php");
	});
	$("#LoadBackgroundContentOff").click(function(){
		$("#RemoveCanvas").remove();
	});
	$("#LightMode").click(function(){
		$(".MainWindow").css("background-color","aliceblue");
		$(".FullProgram").css("background-color","lavender");
	});
	$("#DarkMode").click(function(){
		$(".MainWindow").css("background-color","slategrey");
		$(".FullProgram").css("background-color","dimgrey");
	});
	$("#ResetMode").click(function(){
		$(".MainWindow").css("background-color","ghostwhite");
		$(".FullProgram").css("background-color","ghostwhite");
	});
	$("#Reset").click(function(){
		$("#LoadContent").empty();
	});
});